[package]
distribution = "2201.13.4"
org = "ballerinax"
name = "ardoq"
version = "@toml.version@"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = [] # TODO: Add keywords
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-ardoq"

[build-options]
observabilityIncluded = true

[platform.java21]
graalvmCompatible = true
