[package]
distribution = "2201.13.4"
org = "ballerinax"
name = "ardoq"
version = "1.0.0"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["Name/Ardoq", "Area/Enterprise Architecture", "Vendor/Ardoq", "Cost/Paid", "Type/Connector", "Ardoq", "Enterprise Architecture", "EA"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-ardoq"

[build-options]
observabilityIncluded = true

[platform.java21]
graalvmCompatible = true
